// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlw5R7JbEyBKAfIp9b9QxZO3PNECoKgHM',
    appId: '1:749462259986:web:aebcc5e635f75d6e2e8bcb',
    messagingSenderId: '749462259986',
    projectId: 'flutterauth-4fcc7',
    authDomain: 'flutterauth-4fcc7.firebaseapp.com',
    storageBucket: 'flutterauth-4fcc7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc2L_-DhseqlVHycUKmik9YKOAfZZoU3k',
    appId: '1:749462259986:android:298f02b822ebb16c2e8bcb',
    messagingSenderId: '749462259986',
    projectId: 'flutterauth-4fcc7',
    storageBucket: 'flutterauth-4fcc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWejcxl-tCQQZerGmpRcKoOtIVzMKM1rE',
    appId: '1:749462259986:ios:ddb1565ba7673ab02e8bcb',
    messagingSenderId: '749462259986',
    projectId: 'flutterauth-4fcc7',
    storageBucket: 'flutterauth-4fcc7.firebasestorage.app',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWejcxl-tCQQZerGmpRcKoOtIVzMKM1rE',
    appId: '1:749462259986:ios:ddb1565ba7673ab02e8bcb',
    messagingSenderId: '749462259986',
    projectId: 'flutterauth-4fcc7',
    storageBucket: 'flutterauth-4fcc7.firebasestorage.app',
    iosBundleId: 'com.example.authApp',
  );
}
